import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
import { useState } from "react";
import { HomeComponent } from "../components/Home";
import { Navbar } from "../components/Navbar";

export default function Home() {
  const [state, setstate] = useState("");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="App">
          <Navbar state={state} setstate={setstate} />
          <HomeComponent state={state} setstate={setstate} />
        </div>
    </>
  )
}
